import Field.Adequacy.Canonical
import Field.System.Canonical

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace FieldAdequacyProjection

open FieldAdequacyAPI
open FieldAdequacyCanonical
open FieldAdequacyInstance
open FieldAsyncAPI
open FieldNetworkAPI
open FieldProtocolAPI
open FieldQualityAPI
open FieldQualitySystem
open FieldRouterLifecycle
open FieldSystemCanonical
open FieldSystemEndToEnd

/-- Reduced runtime artifact generated from one lifecycle route in the current
system-facing installed view. This remains a reduced observational projection,
not a new owner of canonical truth. -/
def runtimeArtifactOfLifecycleRoute
    (route : LifecycleRoute) : RuntimeRoundArtifact :=
  { blockedReceive := none
    disposition := HostDisposition.complete
    emittedCount := 0
    stepBudgetRemaining := 0
    routerArtifact := some { lifecycleRoute := route } }

/-- Reduced runtime artifact list projected from the current end-to-end system
state after one `systemStep`. -/
def projectedRuntimeArtifactsOfState
    (state : EndToEndState) : List RuntimeRoundArtifact :=
  ((systemStep state).lifecycle).map runtimeArtifactOfLifecycleRoute

/-- Reduced runtime/system refinement relation generated by the projected
runtime artifact list. -/
def RuntimeExecutionProjectsSystemState
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState) : Prop :=
  artifacts = projectedRuntimeArtifactsOfState state

theorem lifecycleMaintenance_preserves_honest
    (route : LifecycleRoute)
    (hHonest : LifecycleHonest route) :
    LifecycleHonest (lifecycleMaintenance route) := by
  unfold LifecycleHonest at hHonest ⊢
  rw [lifecycle_maintenance_preserves_candidate]
  exact hHonest

theorem maintainLifecycle_mem_implies_honest
    (routes : List LifecycleRoute)
    (hRoutes : ∀ route ∈ routes, LifecycleHonest route)
    (route : LifecycleRoute)
    (hMem : route ∈ maintainLifecycle routes) :
    LifecycleHonest route := by
  unfold maintainLifecycle at hMem
  simp only [List.mem_map] at hMem
  rcases hMem with ⟨source, hSourceMem, hEq⟩
  subst hEq
  exact lifecycleMaintenance_preserves_honest source (hRoutes source hSourceMem)

theorem installLifecycleOfEnvelope_some_implies_honest
    (network : NetworkState)
    (envelope : AsyncEnvelope)
    (route : LifecycleRoute)
    (hInstall : installLifecycleOfEnvelope network envelope = some route) :
    LifecycleHonest route := by
  unfold installLifecycleOfEnvelope at hInstall
  cases hAdmit : admitEnvelopeCandidate network envelope with
  | none =>
      simp [hAdmit] at hInstall
  | some admitted =>
      simp [hAdmit] at hInstall
      subst hInstall
      exact installed_route_is_honest admitted

theorem readyInstalledRoutes_mem_implies_honest
    (state : AsyncState)
    (route : LifecycleRoute)
    (hMem : route ∈ readyInstalledRoutes state) :
    LifecycleHonest route := by
  unfold readyInstalledRoutes at hMem
  rcases List.mem_filterMap.1 hMem with ⟨envelope, _hEnvelopeMem, hSome⟩
  exact installLifecycleOfEnvelope_some_implies_honest (transportStep state).network envelope route hSome

theorem systemStep_lifecycle_mem_implies_honest
    (state : EndToEndState)
    (route : LifecycleRoute)
    (hMem : route ∈ (systemStep state).lifecycle) :
    LifecycleHonest route := by
  unfold systemStep at hMem
  refine maintainLifecycle_mem_implies_honest (routes := readyInstalledRoutes state.async) ?_ route hMem
  intro source hSourceMem
  exact readyInstalledRoutes_mem_implies_honest state.async source hSourceMem

theorem runtimeArtifactOfLifecycleRoute_admitted
    (route : LifecycleRoute)
    (hHonest : LifecycleHonest route) :
    RuntimeArtifactAdmitted (runtimeArtifactOfLifecycleRoute route) := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · simp [runtimeArtifactOfLifecycleRoute]
  · simp [runtimeArtifactOfLifecycleRoute]
  · intro _hTerminal
    rfl
  · intro hBlocked
    simp [runtimeArtifactOfLifecycleRoute] at hBlocked
  · simpa [RuntimeRouterArtifactAdmitted, runtimeArtifactOfLifecycleRoute] using hHonest

theorem projectedRuntimeArtifactsOfState_admitted
    (state : EndToEndState) :
    RuntimeExecutionAdmitted (projectedRuntimeArtifactsOfState state) := by
  intro artifact hMem
  unfold projectedRuntimeArtifactsOfState at hMem
  simp only [List.mem_map] at hMem
  rcases hMem with ⟨route, hRouteMem, hEq⟩
  subst hEq
  exact
    runtimeArtifactOfLifecycleRoute_admitted route
      (systemStep_lifecycle_mem_implies_honest state route hRouteMem)

theorem runtimeLifecycleRoutes_map_runtimeArtifactOfLifecycleRoute
    (routes : List LifecycleRoute) :
    runtimeLifecycleRoutes (routes.map runtimeArtifactOfLifecycleRoute) = routes := by
  induction routes with
  | nil =>
      simp [FieldAdequacyAPI.runtimeLifecycleRoutes]
  | cons route rest ih =>
      have ih' :
          List.filterMap
              ((fun artifact =>
                  Option.map RuntimeRouterArtifact.lifecycleRoute artifact.routerArtifact) ∘
                runtimeArtifactOfLifecycleRoute)
              rest =
            rest := by
        simpa [FieldAdequacyAPI.runtimeLifecycleRoutes] using ih
      simp [FieldAdequacyAPI.runtimeLifecycleRoutes, runtimeArtifactOfLifecycleRoute, ih']

theorem runtimeLifecycleRoutes_projectedRuntimeArtifactsOfState
    (state : EndToEndState) :
    runtimeLifecycleRoutes (projectedRuntimeArtifactsOfState state) =
      (systemStep state).lifecycle := by
  unfold projectedRuntimeArtifactsOfState
  exact runtimeLifecycleRoutes_map_runtimeArtifactOfLifecycleRoute ((systemStep state).lifecycle)

theorem projectedRuntimeArtifactsOfState_projects_system
    (state : EndToEndState) :
    RuntimeExecutionProjectsSystemState (projectedRuntimeArtifactsOfState state) state := by
  rfl

theorem runtimeExecutionProjectsSystemState_implies_alignment
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    RuntimeSystemCanonicalAligned artifacts state := by
  subst hProjection
  exact runtimeLifecycleRoutes_projectedRuntimeArtifactsOfState state

theorem runtime_canonical_route_eq_canonicalSystemRoute_of_projection
    (destination : DestinationClass)
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    runtimeCanonicalRoute destination artifacts =
      canonicalSystemRoute destination state := by
  exact
    runtime_canonical_route_eq_canonicalSystemRoute_of_alignment
      destination artifacts state
      (runtimeExecutionProjectsSystemState_implies_alignment artifacts state hProjection)

theorem runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_projection
    (destination : DestinationClass)
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    runtimeCanonicalRouteView destination artifacts =
      bestSystemRouteView .supportDominance destination state := by
  exact
    runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_alignment
      destination artifacts state
      (runtimeExecutionProjectsSystemState_implies_alignment artifacts state hProjection)

theorem projected_runtime_canonical_route_eq_canonicalSystemRoute
    (destination : DestinationClass)
    (state : EndToEndState) :
    runtimeCanonicalRoute destination (projectedRuntimeArtifactsOfState state) =
      canonicalSystemRoute destination state := by
  exact
    runtime_canonical_route_eq_canonicalSystemRoute_of_projection
      destination
      (projectedRuntimeArtifactsOfState state)
      state
      (projectedRuntimeArtifactsOfState_projects_system state)

theorem projected_runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance
    (destination : DestinationClass)
    (state : EndToEndState) :
    runtimeCanonicalRouteView destination (projectedRuntimeArtifactsOfState state) =
      bestSystemRouteView .supportDominance destination state := by
  exact
    runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_projection
      destination
      (projectedRuntimeArtifactsOfState state)
      state
      (projectedRuntimeArtifactsOfState_projects_system state)

end FieldAdequacyProjection
