import Field.Adequacy.Canonical
import Field.System.Canonical

/-
The Problem. The low-level adequacy alignment theorem still takes an explicit
runtime/system lifecycle equality hypothesis. This file discharges that burden
for the reduced projected-runtime story by generating runtime artifacts from the
system lifecycle view itself and proving the resulting artifacts are admitted.

Solution Structure.
1. Define the reduced runtime projection from lifecycle routes and system
   states.
2. Prove honesty/admission lemmas for projected artifacts.
3. Derive the stronger no-extra-hypothesis runtime/system canonical theorems.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace FieldAdequacyProjection

open FieldAdequacyAPI
open FieldAdequacyCanonical
open FieldAdequacyInstance
open FieldAsyncAPI
open FieldNetworkAPI
open FieldProtocolAPI
open FieldQualityAPI
open FieldQualitySystem
open FieldRouterLifecycle
open FieldSystemCanonical
open FieldSystemEndToEnd

/-! ## Projected Runtime Artifacts -/

/-- Reduced runtime artifact generated from one lifecycle route in the current
system-facing installed view. This remains a reduced observational projection,
not a new owner of canonical truth. -/
def runtimeArtifactOfLifecycleRoute
    (route : LifecycleRoute) : RuntimeRoundArtifact :=
  { blockedReceive := none
    disposition := HostDisposition.complete
    emittedCount := 0
    stepBudgetRemaining := 0
    routerArtifact := some { lifecycleRoute := route } }

def runtimeArtifactsOfRoutes
    (routes : List LifecycleRoute) : List RuntimeRoundArtifact :=
  routes.map runtimeArtifactOfLifecycleRoute

/-- Reduced runtime artifact list projected from the current end-to-end system
state after one `systemStep`. -/
def projectedRuntimeArtifactsOfState
    (state : EndToEndState) : List RuntimeRoundArtifact :=
  runtimeArtifactsOfRoutes (systemStep state).lifecycle

/-- Reduced runtime/system refinement relation generated by the projected
runtime artifact list. -/
def RuntimeExecutionProjectsSystemState
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState) : Prop :=
  artifacts = projectedRuntimeArtifactsOfState state

/-! ## Honesty And Admission -/

theorem lifecycleMaintenance_preserves_honest
    (route : LifecycleRoute)
    (hHonest : LifecycleHonest route) :
    LifecycleHonest (lifecycleMaintenance route) := by
  unfold LifecycleHonest at hHonest ⊢
  rw [lifecycle_maintenance_preserves_candidate]
  exact hHonest

theorem maintainLifecycle_mem_implies_honest
    (routes : List LifecycleRoute)
    (hRoutes : ∀ route ∈ routes, LifecycleHonest route)
    (route : LifecycleRoute)
    (hMem : route ∈ maintainLifecycle routes) :
    LifecycleHonest route := by
  unfold maintainLifecycle at hMem
  simp only [List.mem_map] at hMem
  rcases hMem with ⟨source, hSourceMem, hEq⟩
  subst hEq
  exact lifecycleMaintenance_preserves_honest source (hRoutes source hSourceMem)

theorem installLifecycleOfEnvelope_some_implies_honest
    (network : NetworkState)
    (envelope : AsyncEnvelope)
    (route : LifecycleRoute)
    (hInstall : installLifecycleOfEnvelope network envelope = some route) :
    LifecycleHonest route := by
  unfold installLifecycleOfEnvelope at hInstall
  cases hAdmit : admitEnvelopeCandidate network envelope with
  | none =>
      simp [hAdmit] at hInstall
  | some admitted =>
      simp [hAdmit] at hInstall
      subst hInstall
      exact installed_route_is_honest admitted

theorem readyInstalledRoutes_mem_implies_honest
    (state : AsyncState)
    (route : LifecycleRoute)
    (hMem : route ∈ readyInstalledRoutes state) :
    LifecycleHonest route := by
  unfold readyInstalledRoutes at hMem
  rcases List.mem_filterMap.1 hMem with ⟨envelope, _hEnvelopeMem, hSome⟩
  exact installLifecycleOfEnvelope_some_implies_honest (transportStep state).network envelope route hSome

theorem systemStep_lifecycle_mem_implies_honest
    (state : EndToEndState)
    (route : LifecycleRoute)
    (hMem : route ∈ (systemStep state).lifecycle) :
    LifecycleHonest route := by
  unfold systemStep at hMem
  refine maintainLifecycle_mem_implies_honest (routes := readyInstalledRoutes state.async) ?_ route hMem
  intro source hSourceMem
  exact readyInstalledRoutes_mem_implies_honest state.async source hSourceMem

theorem runtimeArtifactOfLifecycleRoute_admitted
    (route : LifecycleRoute)
    (hHonest : LifecycleHonest route) :
    RuntimeArtifactAdmitted (runtimeArtifactOfLifecycleRoute route) := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · simp [runtimeArtifactOfLifecycleRoute]
  · simp [runtimeArtifactOfLifecycleRoute]
  · intro _hTerminal
    rfl
  · intro hBlocked
    simp [runtimeArtifactOfLifecycleRoute] at hBlocked
  · simpa [RuntimeRouterArtifactAdmitted, runtimeArtifactOfLifecycleRoute] using hHonest

theorem runtimeArtifactsOfRoutes_admitted
    (routes : List LifecycleRoute)
    (hRoutes : ∀ route ∈ routes, LifecycleHonest route) :
    RuntimeExecutionAdmitted (runtimeArtifactsOfRoutes routes) := by
  intro artifact hMem
  unfold runtimeArtifactsOfRoutes at hMem
  simp only [List.mem_map] at hMem
  rcases hMem with ⟨route, hRouteMem, hEq⟩
  subst hEq
  exact runtimeArtifactOfLifecycleRoute_admitted route (hRoutes route hRouteMem)

theorem projectedRuntimeArtifactsOfState_admitted
    (state : EndToEndState) :
    RuntimeExecutionAdmitted (projectedRuntimeArtifactsOfState state) := by
  exact runtimeArtifactsOfRoutes_admitted (systemStep state).lifecycle
    (fun route hMem =>
      systemStep_lifecycle_mem_implies_honest state route hMem)

/-! ## Projection Properties -/

theorem runtimeLifecycleRoutes_map_runtimeArtifactOfLifecycleRoute
    (routes : List LifecycleRoute) :
    runtimeLifecycleRoutes (routes.map runtimeArtifactOfLifecycleRoute) = routes := by
  induction routes with
  | nil =>
      simp [FieldAdequacyAPI.runtimeLifecycleRoutes]
  | cons route rest ih =>
      calc
        runtimeLifecycleRoutes ((route :: rest).map runtimeArtifactOfLifecycleRoute)
            =
          route :: runtimeLifecycleRoutes (rest.map runtimeArtifactOfLifecycleRoute) := by
              simp [FieldAdequacyAPI.runtimeLifecycleRoutes, runtimeArtifactOfLifecycleRoute,
                runtimeLifecycleRouteOfArtifact]
        _ = route :: rest := by
              rw [ih]

theorem runtimeLifecycleRoutes_projectedRuntimeArtifactsOfState
    (state : EndToEndState) :
    runtimeLifecycleRoutes (projectedRuntimeArtifactsOfState state) =
      (systemStep state).lifecycle := by
  unfold projectedRuntimeArtifactsOfState
  exact runtimeLifecycleRoutes_map_runtimeArtifactOfLifecycleRoute ((systemStep state).lifecycle)

theorem projectedRuntimeArtifactsOfState_projects_system
    (state : EndToEndState) :
    RuntimeExecutionProjectsSystemState (projectedRuntimeArtifactsOfState state) state := by
  rfl

theorem runtimeExecutionProjectsSystemState_implies_alignment
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    RuntimeSystemCanonicalAligned artifacts state := by
  subst hProjection
  exact runtimeLifecycleRoutes_projectedRuntimeArtifactsOfState state

/-! ## Canonical Consequences -/

theorem runtime_canonical_route_eq_canonicalSystemRoute_of_projection
    (destination : DestinationClass)
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    runtimeCanonicalRoute destination artifacts =
      canonicalSystemRoute destination state := by
  -- Reduce the projected-runtime theorem to the lower-level alignment theorem
  -- so this file only owns the projection-specific reasoning.
  exact
    runtime_canonical_route_eq_canonicalSystemRoute_of_alignment
      destination artifacts state
      (runtimeExecutionProjectsSystemState_implies_alignment artifacts state hProjection)

theorem runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_projection
    (destination : DestinationClass)
    (artifacts : List RuntimeRoundArtifact)
    (state : EndToEndState)
    (hProjection : RuntimeExecutionProjectsSystemState artifacts state) :
    runtimeCanonicalRouteView destination artifacts =
      bestSystemRouteView .supportDominance destination state := by
  -- Reuse the same reduction pattern at the route-view level.
  exact
    runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_alignment
      destination artifacts state
      (runtimeExecutionProjectsSystemState_implies_alignment artifacts state hProjection)

theorem projected_runtime_canonical_route_eq_canonicalSystemRoute
    (destination : DestinationClass)
    (state : EndToEndState) :
    runtimeCanonicalRoute destination (projectedRuntimeArtifactsOfState state) =
      canonicalSystemRoute destination state := by
  -- Instantiate the projection theorem with the canonical projected artifact
  -- list generated from the current system state.
  exact
    runtime_canonical_route_eq_canonicalSystemRoute_of_projection
      destination
      (projectedRuntimeArtifactsOfState state)
      state
      (projectedRuntimeArtifactsOfState_projects_system state)

theorem projected_runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance
    (destination : DestinationClass)
    (state : EndToEndState) :
    runtimeCanonicalRouteView destination (projectedRuntimeArtifactsOfState state) =
      bestSystemRouteView .supportDominance destination state := by
  -- Re-express the same projected-runtime agreement on the route-view surface
  -- consumed by the quality layer.
  exact
    runtime_canonical_route_view_eq_bestSystemRouteView_supportDominance_of_projection
      destination
      (projectedRuntimeArtifactsOfState state)
      state
      (projectedRuntimeArtifactsOfState_projects_system state)

end FieldAdequacyProjection
