"""PDF assembly for the active-belief paper report."""

from __future__ import annotations

import re
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    KeepTogether,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
)

from analysis.document import (
    BLOCK_SPACER,
    FIGURE_BLOCK_SPACER,
    INLINE_SPACER,
    PAGE_MARGIN_BOTTOM,
    PAGE_MARGIN_LEFT,
    PAGE_MARGIN_RIGHT,
    PAGE_MARGIN_TOP,
    build_styles as build_analysis_styles,
    figure_flowable,
    make_table,
    markup,
)


def write_pdf_report(
    artifact_dir: Path,
    report_dir: Path,
    pdf_path: Path,
    manuscript_text: str,
    figure_specs: list[dict[str, object]],
    figure_rows: list[dict[str, object]],
) -> None:
    styles = build_styles()
    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        rightMargin=PAGE_MARGIN_RIGHT,
        leftMargin=PAGE_MARGIN_LEFT,
        topMargin=PAGE_MARGIN_TOP,
        bottomMargin=PAGE_MARGIN_BOTTOM,
    )
    story: list[object] = []
    story.append(
        Paragraph(
            paper_markup("Active Belief Diffusion With Coded Evidence"),
            styles["TitleCustom"],
        )
    )
    story.append(Spacer(1, INLINE_SPACER))
    story.append(
        Paragraph(
            paper_markup(
                "A standalone active-belief paper artifact generated by analysis_2. "
                "This PDF is separate from the route-visible router tuning analysis and contains the paper text, theorem/task tables, and generated figures."
            ),
            styles["Body"],
        )
    )
    add_markdown(story, styles, manuscript_text)
    add_figures(story, styles, report_dir, figure_specs)
    add_manifest(story, styles, artifact_dir, figure_rows)
    doc.build(story)


def build_styles():
    styles = build_analysis_styles()
    styles.add(
        ParagraphStyle(
            name="SmallCode",
            parent=styles["Code"],
            fontSize=7,
            leading=8,
            leftIndent=8,
        )
    )
    return styles


def add_figures(
    story: list[object],
    styles,
    report_dir: Path,
    figure_specs: list[dict[str, object]],
) -> None:
    story.append(PageBreak())
    story.append(Paragraph("Figures", styles["Section"]))
    for spec in figure_specs:
        story.append(
            KeepTogether(
                [
                    Paragraph(
                        paper_markup(f"Figure {spec['figure_index']}. {spec['figure_name']}"),
                        styles["Subsection"],
                    ),
                    figure_flowable(
                        report_dir,
                        str(spec["figure_id"]),
                        16.4 * cm,
                        7.4 * cm,
                    ),
                    Paragraph(paper_markup(str(spec["caption"])), styles["Caption"]),
                ]
            )
        )
        story.append(Spacer(1, FIGURE_BLOCK_SPACER))


def add_manifest(
    story: list[object],
    styles,
    artifact_dir: Path,
    figure_rows: list[dict[str, object]],
) -> None:
    story.append(PageBreak())
    story.append(Paragraph("Reproducibility Manifest", styles["Section"]))
    table_rows: list[list[str]] = []
    for row in figure_rows:
        table_rows.append(
            [
                str(row["figure_index"]),
                str(row["figure_name"]),
                str(row["source_artifact"]),
                str(row["artifact_row_count"]),
            ]
        )
    story.append(
        make_table(
            ["#", "Figure", "Source", "Rows"],
            table_rows,
            styles,
            [1.0, 5.0, 7.0, 2.0],
        )
    )
    story.append(Spacer(1, BLOCK_SPACER))
    story.append(Paragraph(paper_markup(f"Report artifacts: {artifact_dir}"), styles["Body"]))


def add_markdown(story: list[object], styles, markdown: str) -> None:
    if not markdown.strip():
        return
    paragraph_lines: list[str] = []
    table_lines: list[str] = []
    code_lines: list[str] = []
    in_code = False

    def flush_paragraph() -> None:
        if not paragraph_lines:
            return
        text = " ".join(line.strip() for line in paragraph_lines).strip()
        paragraph_lines.clear()
        if text:
            story.append(Paragraph(paper_markup(text), styles["Body"]))
            story.append(Spacer(1, INLINE_SPACER))

    def flush_table() -> None:
        if not table_lines:
            return
        rows = markdown_table_rows(table_lines)
        table_lines.clear()
        if rows:
            story.append(markdown_table(rows, styles))
            story.append(Spacer(1, BLOCK_SPACER))

    def flush_code() -> None:
        if not code_lines:
            return
        story.append(Preformatted("\n".join(code_lines), styles["SmallCode"]))
        code_lines.clear()
        story.append(Spacer(1, BLOCK_SPACER))

    for raw_line in markdown.splitlines():
        line = raw_line.rstrip()
        if line.startswith("```"):
            if in_code:
                flush_code()
                in_code = False
            else:
                flush_paragraph()
                flush_table()
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        if line.startswith("|"):
            flush_paragraph()
            table_lines.append(line)
            continue
        flush_table()
        if not line.strip():
            flush_paragraph()
            continue
        if line.startswith("# "):
            flush_paragraph()
            story.append(Paragraph(paper_markup(line[2:].strip()), styles["TitleCustom"]))
        elif line.startswith("## "):
            flush_paragraph()
            story.append(Paragraph(paper_markup(line[3:].strip()), styles["Section"]))
        elif line.startswith("### "):
            flush_paragraph()
            story.append(Paragraph(paper_markup(line[4:].strip()), styles["Subsection"]))
        elif line.startswith("- "):
            flush_paragraph()
            story.append(
                Paragraph(
                    paper_markup(line[2:].strip()),
                    styles["BulletBody"],
                    bulletText="\u2022",
                )
            )
        elif numbered_list_line(line):
            flush_paragraph()
            story.append(Paragraph(paper_markup(line.strip()), styles["Body"]))
        elif line.startswith("> "):
            paragraph_lines.append(line[2:])
        else:
            paragraph_lines.append(line)
    flush_paragraph()
    flush_table()
    flush_code()


def markdown_table(rows: list[list[str]], styles):
    column_labels = rows[0]
    body_rows = rows[1:]
    return make_table(column_labels, body_rows, styles, [1.0 for _ in column_labels])


def markdown_table_rows(lines: list[str]) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in lines:
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if cells and all(set(cell) <= {"-", ":", " "} for cell in cells):
            continue
        rows.append(cells)
    return rows


def numbered_list_line(line: str) -> bool:
    prefix, _, rest = line.strip().partition(".")
    return prefix.isdigit() and bool(rest.strip())


def paper_markup(text: str) -> str:
    rendered = markup(text)
    return re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", rendered)
