use super::{
    FieldAttractorPolicy, FieldBootstrapContinuityPolicy, FieldContinuationPolicy,
    FieldContinuityPolicy, FieldEvidencePolicy, FieldObserverEvidencePolicy, FieldPolicy,
    FieldPosturePolicy, FieldPromotionPolicy, FieldPublicationPolicy, FieldRegimePolicy,
    FieldReplayEvidencePolicy, FieldRuntimeContinuityPolicy, FieldSummaryDecayPolicy,
};

pub(crate) const DEFAULT_FIELD_POLICY: FieldPolicy = FieldPolicy {
    regime: FieldRegimePolicy {
        fallback_risk_pressure_permille: 800,
        destination_count_strength_step_permille: 20,
        dwell_ticks: 3,
    },
    posture: FieldPosturePolicy {
        dwell_ticks: 2,
        primary_fast_path_regime_score_floor_permille: 850,
        primary_fast_path_threshold_divisor: 4,
        risk_suppressed_hold_field_strength_floor_permille: 340,
        risk_suppressed_hold_retention_alignment_floor_permille: 300,
        risk_suppressed_hold_relay_alignment_floor_permille: 300,
        risk_suppressed_hold_risk_price_ceiling_permille: 760,
        sparse_opportunistic_bonus_permille: 250,
        sparse_structured_bonus_permille: 150,
        congested_structured_bonus_permille: 250,
        congested_retention_biased_bonus_permille: 200,
        retention_favorable_retention_biased_bonus_permille: 700,
        unstable_risk_suppressed_bonus_permille: 250,
        adversarial_risk_suppressed_bonus_permille: 350,
    },
    continuity: FieldContinuityPolicy {
        steady_support_floor_permille: 300,
        steady_entropy_ceiling_permille: 850,
        bootstrap: FieldBootstrapContinuityPolicy {
            service_support_floor_permille: 130,
            service_top_mass_floor_permille: 140,
            service_entropy_ceiling_permille: 950,
            service_corroborated_branch_count_min: 2,
            service_corroborated_support_floor_permille: 150,
            service_corroborated_retention_floor_permille: 180,
            service_corroborated_top_mass_floor_permille: 160,
            service_corroborated_entropy_ceiling_permille: 940,
            service_corroborated_support_score_floor_permille: 420,
            reverse_feedback_node_top_mass_floor_permille: 160,
            reverse_feedback_support_relief_permille: 80,
            reverse_feedback_discovery_top_mass_relief_permille: 40,
            reverse_feedback_discovery_support_relief_permille: 100,
            reverse_feedback_retention_floor_permille: 140,
            reverse_feedback_discovery_retention_floor_permille: 130,
            reverse_feedback_coherent_sources_min: 1,
            reverse_feedback_discovery_coherent_sources_min: 1,
            forward_propagated_service_top_mass_floor_permille: 220,
            forward_propagated_service_retention_floor_permille: 160,
            forward_propagated_service_combined_support_floor_permille: 520,
            forward_propagated_shared_top_mass_floor_permille: 180,
            forward_propagated_shared_retention_floor_permille: 140,
            forward_propagated_shared_combined_support_floor_permille: 460,
            forward_propagated_shared_coherent_sources_min: 2,
            forward_propagated_discovery_top_mass_relief_permille: 80,
            forward_propagated_discovery_retention_floor_permille: 130,
            forward_propagated_discovery_combined_support_bonus_permille: 160,
            discovery_service_support_score_floor_permille: 420,
        },
        continuation: FieldContinuationPolicy {
            service_pending_retention_floor_permille: 140,
            service_pending_support_floor_permille: 120,
            service_pending_uncertainty_ceiling_permille: 880,
            node_pending_retention_floor_permille: 80,
            node_pending_support_floor_permille: 100,
            node_pending_uncertainty_ceiling_permille: 920,
            service_shift_quality_margin_permille: 140,
            service_shift_downstream_margin_permille: 100,
            node_selection_support_floor_permille: 160,
            service_runtime_support_floor_permille: 180,
            node_runtime_support_floor_permille: 140,
            service_frontier_viability_support_floor_permille: 220,
            service_frontier_viability_retention_floor_permille: 160,
            service_forward_viability_support_floor_permille: 180,
            service_forward_viability_retention_floor_permille: 140,
            service_forward_viability_uncertainty_ceiling_permille: 860,
            service_viable_branch_count_min: 2,
            node_frontier_viability_support_floor_permille: 160,
            node_frontier_viability_retention_floor_permille: 100,
            node_forward_viability_support_floor_permille: 140,
            node_forward_viability_retention_floor_permille: 80,
            node_forward_viability_uncertainty_ceiling_permille: 920,
            node_viable_branch_count_min: 1,
            synthesized_rank_penalty_permille: 20,
            synthesized_reachability_bonus_permille: 60,
            synthesized_selected_neighbor_bonus_permille: 100,
            synthesized_retention_bonus_permille: 60,
            transmission_divergence_trigger_permille: 100,
            transmission_weak_support_floor_permille: 260,
            transmission_retention_affinity_floor_permille: 320,
        },
        runtime: FieldRuntimeContinuityPolicy {
            route_failure_support_floor_permille: 180,
            route_weak_support_floor_permille: 220,
            bootstrap_failure_support_floor_permille: 140,
            degraded_steady_failure_support_floor_permille: 160,
            bootstrap_stale_ticks_max: 5,
            degraded_steady_stale_ticks_max: 6,
            envelope_shift_support_delta_max_permille: 120,
            service_shift_delta_bonus_permille: 30,
            discovery_shift_delta_bonus_permille: 40,
            degraded_shift_delta_bonus_permille: 30,
            support_floor_relief_permille: 40,
            retention_biased_hold_congestion_price_floor_permille: 850,
        },
    },
    promotion: FieldPromotionPolicy {
        stable_support_floor_permille: 220,
        stable_retention_floor_permille: 240,
        stable_top_mass_floor_permille: 220,
        stable_entropy_ceiling_permille: 925,
        weak_support_growth_bonus_permille: 25,
        strong_support_floor_permille: 320,
        strong_retention_floor_permille: 300,
        strong_top_mass_floor_permille: 300,
        strong_entropy_ceiling_permille: 775,
        support_growth_delta_permille: 40,
        uncertainty_reduction_delta_permille: 50,
        anti_entropy_divergence_ceiling_permille: 180,
        anti_entropy_relaxed_divergence_ceiling_permille: 260,
        anti_entropy_retention_floor_permille: 240,
        anti_entropy_relaxed_retention_floor_permille: 180,
        anti_entropy_delivery_bonus_permille: 80,
        anti_entropy_relaxed_delivery_bonus_permille: 120,
        anti_entropy_recent_publication_ticks: 6,
        anti_entropy_relaxed_recent_publication_ticks: 8,
        coherence_best_neighbor_bonus_permille: 140,
        coherence_relaxed_downstream_bonus_permille: 80,
        fresh_neighbor_ticks: 4,
        relaxed_fresh_neighbor_ticks: 7,
    },
    evidence: FieldEvidencePolicy {
        publication: FieldPublicationPolicy {
            service_neighbor_retention_floor_permille: 140,
            service_neighbor_support_floor_permille: 120,
            service_neighbor_uncertainty_ceiling_permille: 900,
            service_evidence_score_bonus_permille: 120,
            service_frontier_score_bonus_permille: 80,
            node_evidence_score_bonus_permille: 160,
            node_frontier_score_bonus_permille: 120,
            node_support_floor_min_permille: 120,
            service_corroborating_frontier_support_floor_permille: 180,
            service_corroborating_frontier_net_value_floor_permille: 200,
            corroboration_branch_bonus_permille: 80,
            service_freshness_weight_min_permille: 25,
            service_freshness_weight_max_permille: 200,
        },
        observer: FieldObserverEvidencePolicy {
            service_carry_forward_freshness_ticks: 3,
            node_carry_forward_freshness_ticks: 5,
            service_carry_forward_retention_floor_permille: 220,
            service_carry_forward_support_floor_permille: 180,
            node_carry_forward_retention_floor_permille: 140,
            node_carry_forward_support_floor_permille: 120,
            service_delivery_bonus_permille: 100,
            service_delivery_decay_step_permille: 25,
            node_delivery_bonus_permille: 60,
            service_retention_bonus_permille: 150,
            service_retention_decay_step_permille: 40,
            node_retention_bonus_permille: 80,
            synthesized_node_publication_staleness_slack_ticks: 3,
            synthesized_node_support_relief_permille: 60,
            synthesized_node_support_floor_min_permille: 140,
            synthesized_node_retention_floor_permille: 180,
            synthesized_node_rank_penalty_permille: 20,
            synthesized_node_selected_neighbor_bonus_permille: 100,
            synthesized_node_reachability_bonus_permille: 120,
            synthesized_node_retention_bonus_permille: 80,
            replay_bridge_support_bonus_permille: 150,
            replay_bridge_retention_bonus_permille: 190,
            replay_high_retention_floor_permille: 560,
            replay_medium_retention_floor_permille: 320,
            replay_high_uncertainty_relief_permille: 120,
            replay_medium_uncertainty_relief_permille: 80,
            replay_low_uncertainty_relief_permille: 40,
            replay_publication_retention_relief_permille: 25,
            prune_extended_retention_floor_permille: 300,
            prune_extended_support_floor_permille: 180,
            prune_moderate_retention_floor_permille: 240,
        },
        replay: FieldReplayEvidencePolicy {
            low_coherence_score_floor_permille: 350,
            retention_replay_support_floor_permille: 520,
            retention_replay_relaxed_support_floor_permille: 450,
            retention_replay_uncertainty_floor_permille: 700,
            stale_primary_ticks: 5,
        },
        summary_decay: FieldSummaryDecayPolicy {
            retention_bias_floor_permille: 200,
            retention_bias_cap_permille: 520,
            sparse_relief_uncertainty_ceiling_permille: 760,
            sparse_relief_bonus_permille: 50,
            reverse_feedback_retention_floor_permille: 160,
            reverse_feedback_uncertainty_ceiling_permille: 820,
            reverse_feedback_bonus_permille: 70,
            forward_propagated_retention_floor_permille: 220,
            forward_propagated_support_floor_permille: 180,
            forward_propagated_uncertainty_ceiling_permille: 820,
            forward_propagated_bonus_permille: 90,
            fallback_bonus_permille: 60,
            reflected_uncertainty_penalty_permille: 200,
            reverse_feedback_uncertainty_penalty_permille: 100,
            sparse_regime_uncertainty_penalty_permille: 50,
            congested_regime_uncertainty_penalty_permille: 100,
            retention_favorable_regime_uncertainty_penalty_permille: 50,
            unstable_regime_uncertainty_penalty_permille: 200,
            adversarial_regime_uncertainty_penalty_permille: 300,
        },
        attractor: FieldAttractorPolicy {
            sparse_relay_alignment_divisor: 4,
            congested_alignment_divisor: 4,
            retention_affinity_divisor: 4,
            unstable_risk_alignment_divisor: 4,
            opportunistic_risk_relief_divisor: 5,
            structured_alignment_divisor: 4,
            retention_biased_affinity_divisor: 4,
            risk_suppressed_alignment_divisor: 4,
            penalty_divisor: 3,
        },
    },
};
